"""multi database edit

Revision ID: 31a4d298dacd
Revises: a7d983cd3a88
Create Date: 2025-05-12 03:05:15.499301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a4d298dacd'
down_revision: Union[str, None] = 'a7d983cd3a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('preferred_job_location', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('preferred_job_type', sa.String(length=100), nullable=True))
    op.execute('ALTER TABLE users ALTER COLUMN education TYPE JSON USING education::json')
    op.execute('ALTER TABLE users ALTER COLUMN experience TYPE JSON USING experience::json')

    op.alter_column('users', 'experience',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE users ALTER COLUMN education TYPE TEXT USING education::text')
    op.execute('ALTER TABLE users ALTER COLUMN experience TYPE TEXT USING experience::text')

    op.drop_column('users', 'preferred_job_type')
    op.drop_column('users', 'preferred_job_location')
    op.drop_column('users', 'summary')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
