"""remove_job_id_from_cv

Revision ID: a7d983cd3a88
Revises: d2f0e0cc6dcc
Create Date: 2025-05-08 18:46:25.464204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d983cd3a88'
down_revision: Union[str, None] = 'd2f0e0cc6dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cvs_job_id_fkey', 'cvs', type_='foreignkey')
    op.drop_column('cvs', 'job_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cvs', sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cvs_job_id_fkey', 'cvs', 'job_recommendations', ['job_id'], ['id'])
    # ### end Alembic commands ###
