"""Add file_path to CV

Revision ID: d2f0e0cc6dcc
Revises: 87d0ec53115b
Create Date: 2025-05-08 02:28:18.553428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f0e0cc6dcc'
down_revision: Union[str, None] = '87d0ec53115b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cvs', sa.Column('file_path', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cvs', 'file_path')
    # ### end Alembic commands ###
