"""added_more_to_job_recommendation

Revision ID: d3fabd65a25e
Revises: e1522bff7f47
Create Date: 2025-05-18 12:18:19.894327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3fabd65a25e'
down_revision: Union[str, None] = 'e1522bff7f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_recommendations', sa.Column('posted', sa.String(length=100), nullable=True))
    op.add_column('job_recommendations', sa.Column('experience_level', sa.String(length=100), nullable=True))
    op.add_column('job_recommendations', sa.Column('skills_required', sa.Text(), nullable=True))
    op.add_column('job_recommendations', sa.Column('job_type', sa.String(length=100), nullable=True))
    op.add_column('job_recommendations', sa.Column('deadline', sa.String(length=100), nullable=True))
    op.drop_column('job_recommendations', 'match_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_recommendations', sa.Column('match_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('job_recommendations', 'deadline')
    op.drop_column('job_recommendations', 'job_type')
    op.drop_column('job_recommendations', 'skills_required')
    op.drop_column('job_recommendations', 'experience_level')
    op.drop_column('job_recommendations', 'posted')
    # ### end Alembic commands ###
