"""replaced the initial generate format with mapping loaction dictionary

Revision ID: df75dce7fa17
Revises: d3fabd65a25e
Create Date: 2025-05-19 00:44:19.456679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df75dce7fa17'
down_revision: Union[str, None] = 'd3fabd65a25e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location_worktype_map', sa.JSON(), nullable=True))
    op.drop_column('users', 'preferred_locations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_locations', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('users', 'location_worktype_map')
    # ### end Alembic commands ###
