"""added missing fields from front end and made names match

Revision ID: e1522bff7f47
Revises: 31a4d298dacd
Create Date: 2025-05-13 15:06:01.401337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1522bff7f47'
down_revision: Union[str, None] = '31a4d298dacd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_titles', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('min_salary', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('preferred_locations', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('employment_type', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('experience_level', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('preferred_industries', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('job_keywords', sa.String(length=150), nullable=True))
    op.drop_column('users', 'salary_expectation')
    op.drop_column('users', 'role')
    op.drop_column('users', 'preferred_job_type')
    op.drop_column('users', 'preferred_job_location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_job_location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('preferred_job_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('salary_expectation', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('users', 'job_keywords')
    op.drop_column('users', 'preferred_industries')
    op.drop_column('users', 'experience_level')
    op.drop_column('users', 'employment_type')
    op.drop_column('users', 'preferred_locations')
    op.drop_column('users', 'min_salary')
    op.drop_column('users', 'preferred_titles')
    # ### end Alembic commands ###
